defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  docs:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create the docs
          command: npx docpress b
      - run:
          name: Set git user
          command: cat ./scripts/v1/git/user | sh -s a1vy a01101100vy@gmail.com
      - run:
          name: Push to gh-pages
          command: cat ./scripts/v1/gh/pages | sh -s gh-pages/.
      - run:
          name: Notify
          command: cat ./scripts/v1/webhook | sh -s $WEBHOOK ./self/.webhook.json

workflows:
  version: 2
  ci-cd:
    jobs:
      - docs:
          filters:
            branches:
              only:
                - master

experimental:
  notify:
    branches:
      only:
        - master
