defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  docs:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run the webhook
          command: cat ./docs/v1/webhook | sh -s $WEBHOOK ./self/.webhook.json
      - run:
          name: Build the docs
          command: npx markt README.md ./docs/index.html ./docs.template.html
      - run:
          name: Set git user
          command: cat ./docs/v1/git/user | sh -s a1vy a01101100vy@gmail.com
      - run:
          name: Update repo
          command: cat ./docs/v1/git/update | sh

workflows:
  version: 2
  ci-cd:
    jobs:
      - docs:
          filters:
            branches:
              only:
                - master

experimental:
  notify:
    branches:
      only:
        - master
